version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    maxBytes: 1024000
    backupCount: 3
loggers:
  sampleLogger:
    level: INFO
    handlers: [console,file]
    propagate: no
root:
  level: INFO
  handlers: [console,file]